[package]
name = "flowsplice-pty-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []
snappy-encode = ["flowsplice-pty-codec/encode"]

[dependencies]
anyhow.workspace = true
flowsplice-pty-codec.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio.workspace = true

[lints]
workspace = true
