import {beforeEach,expect,test,vi} from 'vitest';
const terminals:any[]=[];
vi.mock('@xterm/xterm',()=>({Terminal:class {options={};parser={registerOscHandler:vi.fn()};onInput:any;constructor(){terminals.push(this)}loadAddon(){}open(){}onData(fn:any){this.onInput=fn}onResize(){}resize(){}focus(){}dispose=vi.fn();write=vi.fn();}}));
vi.mock('@xterm/addon-fit',()=>({FitAddon:class{proposeDimensions(){return {cols:80,rows:24}}}}));
let actions:any[]=[];
const receive=(event:any)=>window.flowsplice.receive(event);
const click=(id:string)=>(document.getElementById(id) as HTMLButtonElement).click();
const response=(result:any,request_id='r')=>receive({type:'protocol',message:{type:'response',request_id,result}});
function attach(mode='read_only'){response({status:'attached',session:{id:'session',writer:null},attachment_id:'attachment',mode,writer_epoch:3});}
beforeEach(async()=>{delete window.flowsplicePlatform;delete window.webkit;vi.resetModules();terminals.length=0;actions=[];document.body.innerHTML='<main id="app"></main>';window.FlowSpliceNative={send:(json:string)=>actions.push(JSON.parse(json))};vi.stubGlobal('ResizeObserver',class{observe(){}});HTMLDialogElement.prototype.showModal=function(){this.open=true};HTMLDialogElement.prototype.close=function(){this.open=false};await import('../src/main');receive({type:'state',installed:true,connected:true,busy:false});receive({type:'protocol',message:{type:'hello',can_write:true}});});
test('list first and concurrent New guard until submitted matching response',()=>{expect(actions).toEqual([]);response({status:'sessions',sessions:[]});expect(terminals).toHaveLength(0);click('new');click('new');expect(actions.filter(a=>a.operation?.op==='new')).toHaveLength(1);receive({type:'submitted',request_id:'new',operation:{op:'new'}});response({status:'error',message:'failed'},'new');expect((document.getElementById('new') as HTMLButtonElement).disabled).toBe(false);click('refresh');expect(actions.at(-1).operation.op).toBe('list');});
test('read-only input suppressed and captured epoch never retagged',()=>{attach();terminals[0].onInput('secret');expect(actions.filter(a=>a.operation?.op==='input')).toHaveLength(0);receive({type:'protocol',message:{type:'ownership',session_id:'session',epoch:9,writer:{attachment_id:'attachment'}}});terminals[0].onInput('€'.repeat(6000));const inputs=actions.filter(a=>a.operation?.op==='input');expect(inputs).toHaveLength(2);expect(inputs.every(a=>a.operation.data.length<=16384&&a.operation.writer_epoch===9)).toBe(true);receive({type:'protocol',message:{type:'ownership',session_id:'session',epoch:10,writer:null}});expect(inputs[0].operation.writer_epoch).toBe(9);});
test('takeover warns and changed epoch requires fresh request',()=>{attach();click('mode');receive({type:'submitted',request_id:'take',operation:actions.at(-1).operation});response({status:'takeover_required',session_id:'session',epoch:4,writer:{label:'remote',travel_id:'travel'}},'take');expect(document.getElementById('warning')?.textContent).toContain('remote');receive({type:'protocol',message:{type:'ownership',session_id:'session',epoch:5,writer:null}});click('confirm-takeover');expect(actions.at(-1).operation).toMatchObject({force:false,expected_epoch:null,attachment_id:'attachment'});receive({type:'submitted',request_id:'again',operation:actions.at(-1).operation});response({status:'takeover_required',session_id:'session',epoch:5,writer:{label:'other'}},'again');click('confirm-takeover');expect(actions.at(-1).operation).toMatchObject({force:true,expected_epoch:5});});
test('disconnect disposes terminals; reconnect never rejoins',()=>{attach('read_write');click('disconnect');expect(terminals[0].dispose).toHaveBeenCalled();const count=actions.length;receive({type:'state',installed:true,connected:true,busy:false});expect(actions.length).toBe(count);expect(document.getElementById('tabs')?.children).toHaveLength(0);});

test('native batch waits for terminal parsing before advancing events',async()=>{attach('read_write');let parsed:(()=>void)|undefined;terminals[0].write.mockImplementation((_bytes:any,callback:()=>void)=>{parsed=callback});let done=false;const batch=window.flowsplice.receiveBatch([{type:'protocol',message:{type:'output',attachment_id:'attachment',data:[79,75]}},{type:'protocol',message:{type:'ownership',session_id:'session',epoch:10,writer:null}}]).then(()=>{done=true});await Promise.resolve();expect(done).toBe(false);expect(document.getElementById('mode-label')?.textContent).toBe('读写');expect(parsed).toBeTypeOf('function');parsed!();await batch;expect(done).toBe(true);expect(document.getElementById('mode-label')?.textContent).toBe('只读');});

test('macOS uses its full keyboard without the mobile shortcut row',async()=>{vi.resetModules();window.flowsplicePlatform='macos';document.body.innerHTML='<main id="app"></main>';await import('../src/main');expect(document.getElementById('keys')?.hidden).toBe(true);expect(document.querySelectorAll('#keys button')).toHaveLength(0);});
test('mobile clients retain terminal shortcut keys',()=>{expect(document.getElementById('keys')?.hidden).toBe(false);expect(document.querySelectorAll('#keys button')).toHaveLength(7);});

test('Apple readiness is announced only after the page bridge is installed',async()=>{vi.resetModules();delete window.FlowSpliceNative;const ready=vi.fn((json:string)=>{expect(typeof window.flowsplice.receiveBatch).toBe('function');expect(JSON.parse(json)).toEqual({op:'ready'});});window.webkit={messageHandlers:{pty:{postMessage:ready}}};document.body.innerHTML='<main id="app"></main>';await import('../src/main');expect(ready).toHaveBeenCalledTimes(1);});
