[package]
name = "flowsplice-travelagent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
e2e-remote-ui = ["flowsplice-travel-core/e2e-remote-ui"]

[dependencies]
anyhow.workspace = true
flowsplice-travel-core.workspace = true

[lints]
workspace = true
