#!/bin/sh
set -e

. /lib/functions.sh

usage() {
	echo "usage: $0 server OUTPUT | relay SECTION OUTPUT" >&2
	exit 2
}

die() {
	echo "flowsplice config: $*" >&2
	exit 1
}

toml_escape() {
	case "$1" in
		*'
'*) die 'multiline UCI values are not supported' ;;
	esac
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

write_string() {
	local key="$1" value="$2" output="$3"
	printf '%s = "%s"\n' "$key" "$(toml_escape "$value")" >>"$output"
}

write_integer() {
	local key="$1" value="$2" output="$3"
	case "$value" in
		''|*[!0-9]*) die "$key must be an unsigned integer" ;;
	esac
	printf '%s = %s\n' "$key" "$value" >>"$output"
}

LIST_OUTPUT=
LIST_FIRST=1
append_list_item() {
	local value="$1"
	[ "$LIST_FIRST" -eq 1 ] || printf ', ' >>"$LIST_OUTPUT"
	printf '"%s"' "$(toml_escape "$value")" >>"$LIST_OUTPUT"
	LIST_FIRST=0
}

write_list() {
	local section="$1" option="$2" key="$3" output="$4"
	LIST_OUTPUT="$output"
	LIST_FIRST=1
	printf '%s = [' "$key" >>"$output"
	config_list_foreach "$section" "$option" append_list_item
	printf ']\n' >>"$output"
}

require_option() {
	local section="$1" option="$2" value
	config_get value "$section" "$option"
	[ -n "$value" ] || die "missing $section.$option"
	printf '%s' "$value"
}

write_relay_endpoint() {
	local section="$1" enabled id connection_mode connect_addr
	config_get_bool enabled "$section" enabled 1
	[ "$enabled" -eq 1 ] || return 0
	id="$(require_option "$section" id)"
	connection_mode="$(require_option "$section" connection_mode)"
	case "$connection_mode" in
		passive) connect_addr="$(require_option "$section" connect_addr)" ;;
		active) connect_addr= ;;
		*) die "$section.connection_mode must be passive or active" ;;
	esac
	printf '\n[[relays]]\n' >>"$RENDER_OUTPUT"
	write_string id "$id" "$RENDER_OUTPUT"
	write_string connection_mode "$connection_mode" "$RENDER_OUTPUT"
	[ -z "$connect_addr" ] || write_string connect_addr "$connect_addr" "$RENDER_OUTPUT"
	RELAY_ENDPOINT_COUNT=$((RELAY_ENDPOINT_COUNT + 1))
}

write_home() {
	local section="$1" id
	id="$(require_option "$section" id)"
	printf '\n[[homes]]\n' >>"$RENDER_OUTPUT"
	write_string id "$id" "$RENDER_OUTPUT"
	HOME_COUNT=$((HOME_COUNT + 1))
}

render_server() {
	local output="$1" tmp section=server
	local id control_listen cert key management_ca deployment_root deployment_trust control_signing_key
	local authorization_state generation_state state_store ui_listen handshake work_ttl max_pending control_snapshot_ttl
	local max_control_connections
	tmp="${output}.tmp.$$"
	trap 'rm -f "$tmp"' EXIT INT TERM
	: >"$tmp"
	id="$(require_option "$section" id)"
	control_listen="$(require_option "$section" control_listen)"
	cert="$(require_option "$section" cert)"
	key="$(require_option "$section" key)"
	management_ca="$(require_option "$section" management_ca)"
	deployment_root="$(require_option "$section" deployment_root_public_key)"
	deployment_trust="$(require_option "$section" deployment_trust)"
	control_signing_key="$(require_option "$section" control_signing_key)"
	authorization_state="$(require_option "$section" travel_authorization_state)"
	generation_state="$(require_option "$section" control_generation_state)"
	state_store="$(require_option "$section" state_store)"
	ui_listen="$(require_option "$section" ui_listen)"
	config_get handshake "$section" handshake_timeout_secs 10
	config_get work_ttl "$section" work_ttl_secs 15
	config_get max_pending "$section" max_pending_work 256
	config_get control_snapshot_ttl "$section" control_snapshot_ttl_secs 120
	config_get max_control_connections "$section" max_control_connections 256
	write_string id "$id" "$tmp"
	write_string control_listen "$control_listen" "$tmp"
	write_string cert "$cert" "$tmp"
	write_string key "$key" "$tmp"
	write_string management_ca "$management_ca" "$tmp"
	write_string deployment_root_public_key "$deployment_root" "$tmp"
	write_string deployment_trust "$deployment_trust" "$tmp"
	write_string control_signing_key "$control_signing_key" "$tmp"
	write_string travel_authorization_state "$authorization_state" "$tmp"
	write_string control_generation_state "$generation_state" "$tmp"
	write_string state_store "$state_store" "$tmp"
	write_string ui_listen "$ui_listen" "$tmp"
	write_integer handshake_timeout_secs "$handshake" "$tmp"
	write_integer work_ttl_secs "$work_ttl" "$tmp"
	write_integer max_pending_work "$max_pending" "$tmp"
	write_integer control_snapshot_ttl_secs "$control_snapshot_ttl" "$tmp"
	write_integer max_control_connections "$max_control_connections" "$tmp"
	RENDER_OUTPUT="$tmp"
	HOME_COUNT=0
	config_foreach write_home home
	[ "$HOME_COUNT" -gt 0 ] || die 'an enabled Server requires at least one home section'
	RELAY_ENDPOINT_COUNT=0
	config_foreach write_relay_endpoint relay_endpoint
	[ "$RELAY_ENDPOINT_COUNT" -gt 0 ] || die 'an enabled Server requires at least one enabled relay_endpoint section'
	mv "$tmp" "$output"
	trap - EXIT INT TERM
}

render_relay() {
	local section="$1" output="$2" tmp
	local id connection_mode management_listen data_listen openwrt_network
	local server_control_addr state_store ui_listen
	local server_id cert key management_ca deployment_root deployment_trust
	local authorization_cache handshake route_ttl max_pending max_management_connections max_data_connections
	tmp="${output}.tmp.$$"
	trap 'rm -f "$tmp"' EXIT INT TERM
	: >"$tmp"
	id="$(require_option "$section" id)"
	connection_mode="$(require_option "$section" connection_mode)"
	management_listen="$(require_option "$section" management_listen)"
	data_listen="$(require_option "$section" data_listen)"
	openwrt_network="$(require_option "$section" openwrt_network)"
	server_id="$(require_option "$section" server_id)"
	case "$connection_mode" in
		active) server_control_addr="$(require_option "$section" server_control_addr)" ;;
		passive) server_control_addr= ;;
		*) die "$section.connection_mode must be passive or active" ;;
	esac
	cert="$(require_option "$section" cert)"
	key="$(require_option "$section" key)"
	management_ca="$(require_option "$section" management_ca)"
	deployment_root="$(require_option "$section" deployment_root_public_key)"
	deployment_trust="$(require_option "$section" deployment_trust)"
	authorization_cache="$(require_option "$section" travel_authorization_cache)"
	state_store="$(require_option "$section" state_store)"
	ui_listen="$(require_option "$section" ui_listen)"
	config_get handshake "$section" handshake_timeout_secs 10
	config_get route_ttl "$section" route_ttl_secs 15
	config_get max_pending "$section" max_pending_routes 256
	config_get max_management_connections "$section" max_management_connections 1024
	config_get max_data_connections "$section" max_data_connections 2048
	write_string id "$id" "$tmp"
	write_string connection_mode "$connection_mode" "$tmp"
	write_string management_listen "$management_listen" "$tmp"
	write_string data_listen "$data_listen" "$tmp"
	write_string openwrt_network "$openwrt_network" "$tmp"
	write_string server_id "$server_id" "$tmp"
	[ -z "$server_control_addr" ] || write_string server_control_addr "$server_control_addr" "$tmp"
	write_string cert "$cert" "$tmp"
	write_string key "$key" "$tmp"
	write_string management_ca "$management_ca" "$tmp"
	write_string deployment_root_public_key "$deployment_root" "$tmp"
	write_string deployment_trust "$deployment_trust" "$tmp"
	write_list "$section" server_spki_pin server_spki_pins "$tmp"
	write_string travel_authorization_cache "$authorization_cache" "$tmp"
	write_string state_store "$state_store" "$tmp"
	write_string ui_listen "$ui_listen" "$tmp"
	write_integer handshake_timeout_secs "$handshake" "$tmp"
	write_integer route_ttl_secs "$route_ttl" "$tmp"
	write_integer max_pending_routes "$max_pending" "$tmp"
	write_integer max_management_connections "$max_management_connections" "$tmp"
	write_integer max_data_connections "$max_data_connections" "$tmp"
	mv "$tmp" "$output"
	trap - EXIT INT TERM
}

[ "$#" -ge 2 ] || usage
umask 077
config_load flowsplice

case "$1" in
	server)
		[ "$#" -eq 2 ] || usage
		mkdir -p "$(dirname "$2")"
		render_server "$2"
		;;
	relay)
		[ "$#" -eq 3 ] || usage
		mkdir -p "$(dirname "$3")"
		render_relay "$2" "$3"
		;;
	*) usage ;;
esac
