[package]
name = "flowsplice-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
aws-lc-rs.workspace = true
hex.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
toml.workspace = true
uuid.workspace = true
x509-parser.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
